---
title: "Consequence Table Numbers for May Meeting 2024"
output: html_document
date: "2024-05-16"
---


Load in file and libraries 
```{r, message = FALSE, warning=FALSE}
source("CWD_model_Cross/functions/est_beta_params.R")
source("CWD_model_Cross/functions/allocate_deaths.R")
source("CWD_model_Cross/functions/MyFunctions.R")
source("CWD_model_Cross/cwd_stoch_model_cal_act.r")
source("CWD_model_Cross/ArrivalVectors.R")
source("CWD_model_Cross/functions/cwd_stoch_wrapper_mod.r")
source("CWD_model_Cross/functions/ComHypowSelectH.R") # 2 different functions for setting parameters
source("CWD_model_Cross/functions/ComHypowWeights_even.R") # 2 different functions for setting parameters
source("CWD_model_Cross/functions/Plot_funcs.R") # Basic Plots
source("CWD_model_Cross/functions/CompareAltsFuncwSetH_Plot_func.R") # use for multi strat single H
source("CWD_model_Cross/functions/CompareAltsFunc_Plot_func.R") # use for multi strat across multi H
library(foreach)
library(doParallel)
library(tidyverse)
library(reshape2)
library(patchwork)
```


Run all strategies and average across hypotheses
```{r}
set.seed(666)
setcores <- detectCores() - 1
registerDoParallel(cores=setcores)
setstrats = c("SQ", "Ho", "SK", "NoAA", "PareR", "PventR", "SA")
tempout <- foreach(i = setstrats, .packages = c("dplyr", "tidyr", "stringr", "reshape2")) %dopar% {
  ## Need to load function into loop, might be worth looking into .export          
  source("CWD_model_Cross/functions/ComHypowWeights_even.R")
  simsout <- ComHypowWeights_opt2(selectstrat = i)
  simsout
}

# Note - these are painfully slow... 
### Get counts dataframe  
  for(i in 1:length(setstrats)){
    hold <- tempout[[i]]$counts %>% 
      mutate(strat = setstrats[i])
    if(i == 1){
      count_df <- hold
    }else{
      count_df <- count_df %>% full_join(hold)
    }
  }

### Get surveillance dataframe
  for(i in 1:length(setstrats)){
    hold <- tempout[[i]]$survillance %>% 
      mutate(strat = setstrats[i])
    if(i == 1){
      sharp_df <- hold
    }else{
      sharp_df <- sharp_df %>% full_join(hold)
    }
  }

# simsout_SQ <- ComHypowWeights_opt2(selectstrat = "SQ") 
# simsout_Ho <- ComHypowWeights_opt2(selectstrat = "Ho")   
# simsout_SK <- ComHypowWeights_opt2(selectstrat = "SK")   
# simsout_NoAA <- ComHypowWeights_opt2(selectstrat = "NoAA")   
# simsout_PareR <- ComHypowWeights_opt2(selectstrat = "PareR")   
# simsout_PventR <- ComHypowWeights_opt2(selectstrat = "PventR")   
# simsout_SA <- ComHypowWeights_opt2(selectstrat = "SA")   
# 
# 
# simsout_SQ_counts <- simsout_SQ$counts
# simsout_Ho_counts <- simsout_Ho$counts   
# simsout_SK_counts <- simsout_SK$counts  
# simsout_NoAA_counts <- simsout_NoAA$counts  
# simsout_PareR_counts <- simsout_PareR$counts   
# simsout_PventR_counts <- simsout_PventR$counts  
# simsout_SA_counts <- simsout_SA$counts 
# 
# simsout_SQ_counts$strat <- "SQ"
# simsout_Ho_counts$strat <- "Ho"
# simsout_SK_counts$strat <- "SK"
# simsout_NoAA_counts$strat <- "NoAA"
# simsout_PareR_counts$strat <- "PareR"
# simsout_PventR_counts$strat <- "PventR"
# simsout_SA_counts$strat <- "SA"
# 
# count_df <- simsout_SQ_counts %>% 
#   full_join(simsout_Ho_counts) %>% 
#     full_join(simsout_SK_counts) %>% 
#     full_join(simsout_NoAA_counts) %>% 
#     full_join(simsout_PareR_counts) %>% 
#     full_join(simsout_PventR_counts) %>% 
#     full_join(simsout_SA_counts)
# 
# 
# simsout_SQ_survillance <- simsout_SQ$survillance
# simsout_Ho_survillance <- simsout_Ho$survillance   
# simsout_SK_survillance <- simsout_SK$survillance  
# simsout_NoAA_survillance <- simsout_NoAA$survillance  
# simsout_PareR_survillance <- simsout_PareR$survillance   
# simsout_PventR_survillance <- simsout_PventR$survillance  
# simsout_SA_survillance <- simsout_SA$survillance  
# 
# simsout_SQ_survillance$strat <- "SQ"
# simsout_Ho_survillance$strat <- "Ho"
# simsout_SK_survillance$strat <- "SK"
# simsout_NoAA_survillance$strat <- "NoAA"
# simsout_PareR_survillance$strat <- "PareR"
# simsout_PventR_survillance$strat <- "PventR"
# simsout_SA_survillance$strat <- "SA"
# 
# sharp_df <- simsout_SQ_survillance %>% 
#   full_join(simsout_Ho_survillance) %>% 
#     full_join(simsout_SK_survillance) %>% 
#     full_join(simsout_NoAA_survillance) %>% 
#     full_join(simsout_PareR_survillance) %>% 
#     full_join(simsout_PventR_survillance) %>% 
#     full_join(simsout_SA_survillance)

```

### Current approach

Values need for the consequence table.. 
```{r}
### detection time stamp

    detected_prev <- sharp_df %>%
    filter(population > 0) %>%
    group_by(strat, sim, year, month) %>%
    summarise(detectedprev_count = n()) %>% 
    group_by(strat, sim) %>%
    summarise(min_year = min(year)) %>% 
    group_by(strat) %>% 
    summarise(mean_min_year = mean(min_year))


### Spread/prevalence - The true state of percent prevalence of CWD after 25 years 
Prev_Strat <- count_df %>%
  filter(month %% 12 == 1) %>%
  group_by(strat, year, disease) %>%
  summarise(n = sum(population), .groups = "drop") %>%
  spread(key = disease, value = n) %>%
  mutate(prev = yes / (no + yes)) %>%
  filter(year == 24)


### Average size of the deer population over 25 years (“Population”)
#!! Check the way the averaging is set up here... 


  Popn_Strat <- count_df %>%
    filter(month %% 12 == 11) %>%
    group_by(strat, sim, year) %>%
    dplyr::summarize(n = sum(population) / 4) %>%  # need to divide by 4 (4 hypos..)
    dplyr::summarize(avg = mean(n, na.rm = T)) %>% 
    group_by(strat) %>% 
    dplyr::summarize(strat_avg = round(mean(avg, na.rm = T)))

```


### Average 
```{r}
set.seed(122)
setcores <- detectCores() - 1
registerDoParallel(cores=setcores)
setstrats = c("SQ", "Ho", "SK", "NoAA", "PareR", "PventR", "SA")
tempout <- foreach(i = setstrats, .packages = c("dplyr", "tidyr", "stringr", "reshape2")) %dopar% {
  ## Need to load function into loop, might be worth looking into .export          
  source("CWD_model_Cross/functions/ComHypowAVGarrv.R")
  simsout <- ComHypowWeights_AVG(selectstrat = i)
  simsout
}

# Note - these are painfully slow... 
### Get counts dataframe  
  for(i in 1:length(setstrats)){
    hold <- tempout[[i]]$counts %>% 
      mutate(strat = setstrats[i])
    if(i == 1){
      count_df_avg <- hold
    }else{
      count_df_avg <- count_df_avg %>% full_join(hold)
    }
  }

### Get surveillance dataframe
  for(i in 1:length(setstrats)){
    hold <- tempout[[i]]$survillance %>% 
      mutate(strat = setstrats[i])
    if(i == 1){
      sharp_df_AVG <- hold
    }else{
      sharp_df_AVG <- sharp_df_AVG %>% full_join(hold)
    }
  }

```

Values need for the consequence table.. 
```{r}
### detection time stamp

    detected_prev <- sharp_df_AVG %>%
    filter(population > 0) %>%
    group_by(strat, sim, year, month) %>%
    summarise(detectedprev_count = n()) %>% 
    group_by(strat, sim) %>%
    summarise(min_year = min(year)) %>% 
    group_by(strat) %>% 
    summarise(mean_min_year = mean(min_year))


### Spread/prevalence - The true state of percent prevalence of CWD after 25 years 
Prev_Strat <- count_df_avg %>%
  filter(month %% 12 == 1) %>%
  group_by(strat, year, disease) %>%
  summarise(n = sum(population), .groups = "drop") %>%
  spread(key = disease, value = n) %>%
  mutate(prev = yes / (no + yes)) %>%
  filter(year == 24)


### Average size of the deer population over 25 years (“Population”)
#!! Check the way the averaging is set up here... 


  Popn_Strat <- count_df_avg %>%
    filter(month %% 12 == 11) %>%
    group_by(strat, sim, year) %>%
    dplyr::summarize(n = sum(population) / 4) %>%  # need to divide by 4 (4 hypos..)
    dplyr::summarize(avg = mean(n, na.rm = T)) %>% 
    group_by(strat) %>% 
    dplyr::summarize(strat_avg = round(mean(avg, na.rm = T)))

```


### Arrives year 1 
```{r}

# setcores <- detectCores() - 1
# registerDoParallel(cores=setcores)
# setstrats = c("SQ", "Ho", "SK", "NoAA", "PareR", "PventR", "SA")
# tempout <- foreach(i = setstrats, .packages = c("dplyr", "tidyr", "stringr", "reshape2")) %dopar% {
#   ## Need to load function into loop, might be worth looking into .export          
#   source("CWD_model_Cross/functions/ComHypowarrvyr1.R")
#   simsout <- ComHypowWeights_arrvyr1(selectstrat = i)
#   simsout
# }
# 
# # Note - these are painfully slow... 
# ### Get counts dataframe  
#   for(i in 1:length(setstrats)){
#     hold <- tempout[[i]]$counts %>% 
#       mutate(strat = setstrats[i])
#     if(i == 1){
#       count_df_yr1 <- hold
#     }else{
#       count_df_yr1 <- count_df_yr1 %>% full_join(hold)
#     }
#   }
# 
# ### Get surveillance dataframe
#   for(i in 1:length(setstrats)){
#     hold <- tempout[[i]]$survillance %>% 
#       mutate(strat = setstrats[i])
#     if(i == 1){
#       sharp_df_yr1 <- hold
#     }else{
#       sharp_df_yr1 <- sharp_df_yr1 %>% full_join(hold)
#     }
#   }
source("CWD_model_Cross/functions/ComHypowarrvyr1.R")
set.seed(666)
simsout_SQ <- ComHypowWeights_arrvyr1(selectstrat = "SQ") 
simsout_Ho <- ComHypowWeights_arrvyr1(selectstrat = "Ho")
simsout_SK <- ComHypowWeights_arrvyr1(selectstrat = "SK") ## Will never arrive in year 1 under H2 so only looking at H1 here 
simsout_NoAA <- ComHypowWeights_arrvyr1(selectstrat = "NoAA") ##!!
simsout_PareR <- ComHypowWeights_arrvyr1(selectstrat = "PareR") #true/false
simsout_PventR <- ComHypowWeights_arrvyr1(selectstrat = "PventR")
simsout_SA <- ComHypowWeights_arrvyr1(selectstrat = "SA")## Will never arrive in year 1 under H2 so only looking at H1 here 


simsout_SQ_counts <- simsout_SQ$counts
simsout_Ho_counts <- simsout_Ho$counts
simsout_SK_counts <- simsout_SK$counts
simsout_NoAA_counts <- simsout_NoAA$counts
simsout_PareR_counts <- simsout_PareR$counts
simsout_PventR_counts <- simsout_PventR$counts
simsout_SA_counts <- simsout_SA$counts

simsout_SQ_counts$strat <- "SQ"
simsout_Ho_counts$strat <- "Ho"
simsout_SK_counts$strat <- "SK"
simsout_NoAA_counts$strat <- "NoAA"
simsout_PareR_counts$strat <- "PareR"
simsout_PventR_counts$strat <- "PventR"
simsout_SA_counts$strat <- "SA"

count_df <- simsout_SQ_counts %>%
  full_join(simsout_Ho_counts) %>%
    full_join(simsout_SK_counts) %>%
    full_join(simsout_NoAA_counts) %>%
    full_join(simsout_PareR_counts) %>%
    full_join(simsout_PventR_counts) %>%
    full_join(simsout_SA_counts)


simsout_SQ_survillance <- simsout_SQ$survillance
simsout_Ho_survillance <- simsout_Ho$survillance
simsout_SK_survillance <- simsout_SK$survillance
simsout_NoAA_survillance <- simsout_NoAA$survillance
simsout_PareR_survillance <- simsout_PareR$survillance
simsout_PventR_survillance <- simsout_PventR$survillance
simsout_SA_survillance <- simsout_SA$survillance

simsout_SQ_survillance$strat <- "SQ"
simsout_Ho_survillance$strat <- "Ho"
simsout_SK_survillance$strat <- "SK"
simsout_NoAA_survillance$strat <- "NoAA"
simsout_PareR_survillance$strat <- "PareR"
simsout_PventR_survillance$strat <- "PventR"
simsout_SA_survillance$strat <- "SA"

sharp_df <- simsout_SQ_survillance %>%
  full_join(simsout_Ho_survillance) %>%
    full_join(simsout_SK_survillance) %>%
    full_join(simsout_NoAA_survillance) %>%
    full_join(simsout_PareR_survillance) %>%
    full_join(simsout_PventR_survillance) %>%
    full_join(simsout_SA_survillance)

```

Values need for the consequence table.. 
```{r}
### detection time stamp

    detected_prev <- sharp_df %>%
    filter(population > 0) %>%
    group_by(strat, sim, year, month) %>%
    summarise(detectedprev_count = n()) %>% 
    group_by(strat, sim) %>%
    summarise(min_year = min(year)) %>% 
    group_by(strat) %>% 
    summarise(mean_min_year = mean(min_year))


### Spread/prevalence - The true state of percent prevalence of CWD after 25 years 
Prev_Strat <- count_df %>%
  filter(month %% 12 == 1) %>%
  group_by(strat, year, disease) %>%
  summarise(n = sum(population), .groups = "drop") %>%
  spread(key = disease, value = n) %>%
  mutate(prev = yes / (no + yes)) %>%
  filter(year == 24)


### Average size of the deer population over 25 years (“Population”)
#!! Check the way the averaging is set up here... 


  Popn_Strat <- count_df %>%
    filter(month %% 12 == 11) %>%
    group_by(strat, sim, year) %>%
    dplyr::summarize(n = sum(population) / 4) %>%  # need to divide by 4 (4 hypos..)
    dplyr::summarize(avg = mean(n, na.rm = T)) %>% 
    group_by(strat) %>% 
    dplyr::summarize(strat_avg = round(mean(avg, na.rm = T)))

```