---
title: "Viusal_Action_check"
output: html_document
date: "2024-04-25"
---




set up
```{r}
library(Hmisc)
library(tidyverse)
library(reshape2)

source("functions/est_beta_params.R")
source("functions/allocate_deaths.R")
source("functions/MyFunctions.R")
source("cwd_stoch_model_cal_act.r")
source("ArrivalVectors.R")
source("functions/cwd_stoch_wrapper_mod.r")
```


Run model
```{r}
params <- list(fawn.an.sur = 0.7, juv.an.sur = 0.8, ad.an.f.sur = 0.82,
               ad.an.m.sur = 0.8, fawn.repro = 0.06, juv.repro = 1.3, ad.repro = 1.4,
               hunt.mort.fawn = 0.01, hunt.mort.juv.f = 0.1, hunt.mort.juv.m = 0.1,
               hunt.mort.ad.f = 0.12, hunt.mort.ad.m = 0.50,
               # ini.fawn.prev = (2/10000),
               # ini.juv.prev = (2/10000), ini.ad.f.prev = (2/10000),  ini.ad.m.prev = (2/10000),
                ini.fawn.prev = 0.01,
                ini.juv.prev = 0.03, ini.ad.f.prev = 0.04,  ini.ad.m.prev = 0.04,
               n.age.cats = 12,  n.age.cats.m = 10, n.age.cats.f = 15,
                p = 0.27, env.foi = 0,  beta.f = 0.028,  beta.m = 0.028,
               theta = 0.9, n0 = 10000, n.years = 10, rel.risk = 1.0,
               repro.var = 0.005, fawn.sur.var = 0.005, sur.var = 0.005, hunt.var = 0.0005,
               juv.sur.var = 0.005, ad.f.sur.var = 0.005, ad.m.sur.var = 0.005,
             juv.repro.var = 0.005, ad.repro.var = 0.005,
             WSI = 1,
             arrival_input = c(100,100,1,1,1,1,5, 1, 8, 14), 
             Action_young_bucks = 1, Action_lib_harvest = 1, Action_targetrm = 1, Action_sharpshooting = 1,
             nosampled = 5
)

# simsout <- cwd_stoch_model(params)
simsout <- cwd_stoch_wrapper(params, nsims = 50, n.years, strat, hypothesis)
## Inputs here need to line up.. with params values
```



Get summary stats from arrival vectors 
*Note, things get weird if n.years doesn't = 25
```{r, message=FALSE}
ArrivalVects <- ArrivalVecsFunc(n.years = 25, nsims = 50)
ArrivalVects <- arrivalvec2 
hold <- n.years + 4

ArrivalVects[,5:hold] <- NA

for(i in 1:nrow(ArrivalVects)){
  tempvec <- as.vector(unlist(ArrivalVects$Vec[i]))
  ArrivalVects[i,5:hold] <- t(tempvec)
}

emptyvec <- c()
for(i in 1:25){
  hold <- paste0("time", i)
  if(i == 1){
    emptyvec <- hold
  }else{
      emptyvec <- c(emptyvec, hold)
  }
}

colnames(ArrivalVects) <- c("Strategy" , "Hypo",     "Vec" ,     "sim" , "time1",  "time2",  "time3",  "time4",  "time5",  "time6",  "time7",  "time8", "time9",  "time10", "time11", "time12", "time13", "time14", "time15", "time16", "time17", "time18", "time19", "time20", "time21", "time22" , "time23", "time24",
 "time25")


ArrivalVects_sum <- ArrivalVects %>% 
  dplyr::select(-c(Vec)) %>% 
  group_by(Strategy, Hypo) %>% 
  summarise(across(time1:time25, ~mean(., na.rm = TRUE))) %>% 
  pivot_longer(cols = c("time1",  "time2",  "time3",  "time4",  "time5",  "time6",  "time7",  "time8", "time9",  "time10", "time11", "time12", "time13", "time14", "time15", "time16", "time17", "time18", "time19", "time20", "time21", "time22" , "time23", "time24",
 "time25"), names_to = "time", values_to = "n")

ggplot(data = ArrivalVects_sum,
              aes(x = time, y = n)) +
  geom_point(aes(color = Strategy), position = "jitter") +
  facet_wrap(~Hypo)





```



Heavy Outreach (Ho), Stop Arrival (SA), and Status Quo (SQ) have NO hunting actions
Prevent and React (PventR), Prepare and React (PareR) and No VAAFM (NoAA) have ALL hunting actions

```{r}

```


