---
title: "VT_Calibrate_Visual"
output: word_document
date: "2024-03-19"
---

set up
```{r}
library(Hmisc)
library(tidyverse)
library(reshape2)

source("functions/est_beta_params.R")
source("functions/allocate_deaths.R")
source("cwd_stoch_model_calibrate.r")
source("functions/cwd_stoch_wrapper.r")
```

Run sims
```{r params}

params <- list(fawn.an.sur = 0.7, juv.an.sur = 0.8, ad.an.f.sur = 0.82,
               ad.an.m.sur = 0.8,
             #  fawn.repro = 0.1, juv.repro = 1.3, ad.repro = 1.64, # adjusted from Nick's data. Note popn crashes when change to these
              fawn.repro = 0.06, juv.repro = 1.3, ad.repro = 1.4,
               hunt.mort.fawn = 0.01, hunt.mort.juv.f = 0.1, hunt.mort.juv.m = 0.1,
               hunt.mort.ad.f = 0.12, hunt.mort.ad.m = 0.30,
               ini.fawn.prev = 0.01,
               ini.juv.prev = 0.03, ini.ad.f.prev = 0.04,  ini.ad.m.prev = 0.04,
               n.age.cats = 12, 
             n.age.cats.m = 10, n.age.cats.f = 15, 
                p = 0.27, env.foi = 0,  beta.f = 0.02,  beta.m = 0.02,
               theta = .85, n0 = 1000, n.years = 50, rel.risk = 1.0,
               repro.var = 0.005, fawn.sur.var = 0.005, sur.var = 0.005, hunt.var = 0.0005,
               #my added var params
               juv.sur.var = 0.005, ad.f.sur.var = 0.005, ad.m.sur.var = 0.005,
               #juv.repro.var = 0.68, ad.repro.var = 0.68 # from Nick's data
             juv.repro.var = 0.005, ad.repro.var = 0.005,
             WSI = 1
)

simsout <- cwd_stoch_wrapper(params, nsims = 50)
```

```{r sexratio}
sexratio <- simsout$counts %>% 
  filter(age != 1) %>% 
  filter(month %% 12 == 4) %>% 
  group_by(sim, month, year) %>% 
  dplyr::select(-c(category, age, disease)) %>% 
  pivot_wider(names_from = c(sex), values_from = population, values_fn = ~sum(.x, na.rm = TRUE)) %>% 
  mutate(sexratio = f/m)

mean_sim <- sexratio %>% 
  group_by(year) %>% 
  summarise(sexratio = mean(sexratio),
            sexratio_sd = sd(sexratio)) %>% 
  mutate(upper_CI = sexratio+sexratio_sd, 
         lower_CI = sexratio-sexratio_sd)

ggplot(data = sexratio,
                   aes(x = year, y = sexratio)) +
  geom_line(aes(group = sim), color = "grey", size = 0.5) +
  geom_line(data = mean_sim, color = "black", size = 1) +
  stat_summary(geom="ribbon", fun.data = mean_cl_boot, 
               conf.int=0.95, alpha = 0.0, linetype = "dashed", color = "black", size = .75)+
  geom_hline(yintercept = 2.5, color = "red") +
  ylim(c(0, 4)) +
  labs(x = "time (years)", 
       y = "sex ratio", title = "Sex Ratio Over Time")+
  theme_classic()
```


```{r Abundance}

simsout.count <- simsout$counts
simsout.count$age.cat <- "adult"
simsout.count$age.cat[simsout.count$age == 1] <- "fawn"

dat.sum <- simsout.count %>%
  filter(month %% 12 == 11) %>%
  group_by(year, sim) %>%
  dplyr::summarize(n = sum(population)) %>%
  arrange(sim, year)

# calculate the mean
dat.mean <- dat.sum %>%
  group_by(year) %>%
  dplyr::summarize(avg = mean(n, na.rm = T))

dat.errors <- dat.sum %>%
  group_by(year) %>%
  dplyr::summarize(lo = quantile(n, 0.025, na.rm=T),
                   hi = quantile(n, 0.975, na.rm=T))

ggplot(data = dat.sum, aes(x = year, y = n)) +
  geom_line(color = "grey", aes(group = sim)) +
  geom_line(data = dat.mean, aes(x = year, y = avg), size = 1.5) +
#  geom_hline(yintercept = 143758, color = "red") +
  theme(axis.text=element_text(size=16), axis.title=element_text(size=20))

```

```{r}
#buck abundance
dat.sum.m <- simsout.count %>%
  filter(month %% 12 == 9) %>%
  filter(age != 1 & age !=2) %>%
  filter(sex=="m") %>%
  group_by(year, sim) %>%
  dplyr::summarize(n = sum(population)) %>%
  arrange(sim, year)

# calculate the mean
dat.mean.m <- dat.sum.m %>%
  group_by(year) %>%
  dplyr::summarize(avg = mean(n, na.rm = T))

dat.errors.m <- dat.sum.m %>%
  group_by(year) %>%
  dplyr::summarize(lo = quantile(n, 0.025, na.rm=T),
                   hi = quantile(n, 0.975, na.rm=T))

ggplot(data = dat.sum.m, aes(x = year, y = n)) +
  geom_line(color = "grey", aes(group = sim)) +
  geom_line(data = dat.mean.m, aes(x = year, y = avg), size = 1.5) +
  geom_hline(yintercept = 27729, color = "red") +
  theme(axis.text=element_text(size=16), axis.title=element_text(size=20))


#doe abundance
dat.sum.f <- simsout.count %>%
  filter(month %% 12 == 9) %>%
  filter(age.cat == "adult") %>%
  filter(sex=="f") %>%
  group_by(year, sim) %>%
  dplyr::summarize(n = sum(population)) %>%
  arrange(sim, year)

# calculate the mean
dat.mean.f <- dat.sum.f %>%
  group_by(year) %>%
  dplyr::summarize(avg = mean(n, na.rm = T))

dat.errors.f <- dat.sum.f %>%
  group_by(year) %>%
  dplyr::summarize(lo = quantile(n, 0.025, na.rm=T),
                   hi = quantile(n, 0.975, na.rm=T))

ggplot(data = dat.sum.f, aes(x = year, y = n)) +
  geom_line(color = "grey", aes(group = sim)) +
  geom_line(data = dat.mean.f, aes(x = year, y = avg), size = 1.5) +
  geom_hline(yintercept = 70710, color = "red") +
  theme(axis.text=element_text(size=16), axis.title=element_text(size=20))


#fawn abundance
dat.sum.fawn <- simsout.count %>%
  filter(month %% 12 == 9) %>%
  filter(age.cat == "fawn") %>%
  group_by(year, sim) %>%
  dplyr::summarize(n = sum(population)) %>%
  arrange(sim, year)

# calculate the mean
dat.mean.fawn <- dat.sum.fawn %>%
  group_by(year) %>%
  dplyr::summarize(avg = mean(n, na.rm = T))

dat.errors.fawn <- dat.sum.fawn %>%
  group_by(year) %>%
  dplyr::summarize(lo = quantile(n, 0.025, na.rm=T),
                   hi = quantile(n, 0.975, na.rm=T))

ggplot(data = dat.sum.fawn, aes(x = year, y = n)) +
  geom_line(color = "grey", aes(group = sim)) +
  geom_line(data = dat.mean.fawn, aes(x = year, y = avg), size = 1.5) +
  geom_hline(yintercept = 45000, color = "red") +
  theme(axis.text=element_text(size=16), axis.title=element_text(size=20))

```



Doe:Fawn ratio
Highest I can get this is 1.2 and then the abundance goes exponential 
```{r doe_fawn_ratio}
doe_fawn_ratio <- simsout$counts %>% 
  mutate(IDfawn = case_when(age == 1 ~ "fawns", age != 1 ~  "notfawn")) %>% 
  filter(!(sex == "m" & IDfawn == "notfawn")) %>% 
  filter(month %% 12 == 2) %>%
  dplyr::select(-c(category, age, sex, disease)) %>% 
  pivot_wider(names_from = c(IDfawn), values_from = population, values_fn = ~sum(.x, na.rm = TRUE)) %>% 
  mutate(ratio = fawns/notfawn)

mean_sim <- doe_fawn_ratio %>% 
  group_by(year) %>% 
  summarise(ratio = mean(ratio),
            ratio_sd = sd(ratio)) %>% 
  mutate(upper_CI = ratio+ratio_sd, 
         lower_CI = ratio-ratio_sd)

ggplot(data = doe_fawn_ratio,
                   aes(x = year, y = ratio)) +
  geom_line(aes(group = sim), color = "grey", size = 0.5) +
  geom_line(data = mean_sim, color = "black", size = 1) +
  stat_summary(geom="ribbon", fun.data = mean_cl_boot, 
               conf.int=0.95, alpha = 0.0, linetype = "dashed", color = "black", size = .75)+
  geom_hline(yintercept = 1.5, color = "red") + ## This will depend on pop starting size
  labs(x = "time (years)", 
       y = "Doe:Fawn Ratio", title = "Doe:Fawn Ratio Over Time")+
  theme_classic()

```


Harvest
```{r harvestdf}
mod_deaths_harv <- simsout$deaths %>% 
 filter(month %% 12 == 7) %>%
  filter(population > 0) %>% 
  filter(category == "Ht.f" |category == "Ht.m") %>% 
    mutate(IDfawn = case_when(age == 1 ~ 1, age != 1 ~  0)) %>% 
    mutate(IDjuv = case_when(age == 2 ~ 1, age != 2 ~  0)) %>% 
    mutate(IDadult = case_when(age > 2 ~ 1, age < 2 ~  0)) %>% 
    mutate(IDf = case_when(sex == "f" ~ 1, sex != "f" ~  0)) %>% 
    mutate(IDm = case_when(sex == "m" ~ 1, sex != "m" ~  0)) %>% 
      mutate(FawnCount = population * IDfawn) %>% 
      mutate(JuvCount = population * IDjuv) %>% 
      mutate(AFCount = population * IDadult * IDf) %>% 
      mutate(AMCount = population * IDadult * IDm)  %>% 
  mutate(age_class = ifelse(age == 1, "fawn",
                               ifelse(age == 2, "juv", "adult"))) %>% 
    # mutate(year = round(year * .9)) %>% 
  group_by(sim, year, age_class) %>% 
  dplyr::summarise(dead_fawns = sum(FawnCount),
            dead_juv = sum(JuvCount),
            dead_AF = sum(AFCount),
            dead_AM = sum(AMCount), 
            .groups = 'keep') %>% 
  mutate_at(vars(dead_fawns, dead_juv, dead_AF, dead_AM), replace_na, 0)


mod_counts <- simsout$counts %>% 
  filter(population > 0) %>% 
    mutate(IDfawn = case_when(age == 1 ~ 1, age != 1 ~  0)) %>% 
    mutate(IDjuv = case_when(age == 2 ~ 1, age != 2 ~  0)) %>% 
    mutate(IDadult = case_when(age > 2 ~ 1, age < 2 ~  0)) %>% 
    mutate(IDf = case_when(sex == "f" ~ 1, sex != "f" ~  0)) %>% 
    mutate(IDm = case_when(sex == "m" ~ 1, sex != "m" ~  0)) %>% 
      mutate(FawnCount = population * IDfawn) %>% 
      mutate(JuvCount = population * IDjuv) %>% 
      mutate(AFCount = population * IDadult * IDf) %>% 
      mutate(AMCount = population * IDadult * IDm) %>% 
  mutate(age_class = ifelse(age == 1, "fawn",
                               ifelse(age == 2, "juv", "adult"))) %>% 
    mutate(year = round(year)) %>% 
  group_by(sim, year,age_class) %>% 
  summarise(alive_fawns = sum(FawnCount),
            alive_juv = sum(JuvCount),
            alive_AF = sum(AFCount),
            alive_AM = sum(AMCount)) %>% 
  mutate_at(vars(alive_fawns, alive_juv, alive_AF, alive_AM), replace_na, 0)

harvest_df <- full_join(mod_deaths_harv, mod_counts, by = c("sim", "year", "age_class"))
```



fawn harvest
```{r}
fawn_harv <- mod_deaths_harv %>% 
  filter(age_class == "fawn") %>% 
  mutate(harvest2 = dead_fawns)

mean_sim <- fawn_harv %>% 
  group_by(year) %>% 
  dplyr::summarise(harvest2 = mean(dead_fawns),
            harvest_sd = sd(dead_fawns)) %>% 
  mutate(upper_CI = harvest2+harvest_sd, 
         lower_CI = harvest2-harvest_sd)

ggplot(data = fawn_harv,
                   aes(x = year, y = harvest2)) +
  geom_line(aes(group = sim), color = "grey", size = 0.5) +
  geom_line(data = mean_sim, color = "black", size = 1) +
  stat_summary(geom="ribbon", fun.data = mean_cl_boot, 
               conf.int=0.95, alpha = 0.0, linetype = "dashed", color = "black", size = .75)+
  geom_hline(yintercept = 550, color = "red") + ## This will depend on pop starting size
  labs(x = "time (years)", 
       y = "harvest (n)", title = "Fawn harvest per Year")+
  theme_classic()

```




juvenile harvest
```{r}
juv_harv <- mod_deaths_harv %>% 
  filter(age_class == "juv") %>% 
  mutate(harvest = dead_juv)

mean_sim <- juv_harv %>% 
  group_by(year) %>% 
  summarise(harvest = mean(harvest),
            harvest_sd = sd(harvest)) %>% 
  mutate(upper_CI = harvest+harvest_sd, 
         lower_CI = harvest-harvest_sd)

ggplot(data = juv_harv,
                   aes(x = year, y = harvest)) +
  geom_line(aes(group = sim), color = "grey", size = 0.5) +
  geom_line(data = mean_sim, color = "black", size = 1) +
  stat_summary(geom="ribbon", fun.data = mean_cl_boot, 
               conf.int=0.95, alpha = 0.0, linetype = "dashed", color = "black", size = .75)+
  geom_hline(yintercept = 3680, color = "red") + ## This will depend on pop starting size
    geom_hline(yintercept = 3680 * .1 + 3680, color = "midnightblue") + ## 10% wounding loss + harvest
  labs(x = "time (years)", 
       y = "harvest", title = "Juvenile Harvest per Year")+
  ylim(c(0, 25000))+
  theme_classic()
# 3680 is estimate of number of MALE juvs
```





Adult Female harvest
```{r}
AF_harv <- mod_deaths_harv %>% 
  select(-dead_AM) %>% 
  filter(age_class == "adult") %>% 
  mutate(harvest = dead_AF)

mean_sim <- AF_harv %>% 
  group_by(year) %>% 
  summarise(harvest = mean(harvest),
            harvest_sd = sd(harvest)) %>% 
  mutate(upper_CI = harvest+harvest_sd, 
         lower_CI = harvest-harvest_sd)

ggplot(data = AF_harv,
                   aes(x = year, y = harvest)) +
  geom_line(aes(group = sim), color = "grey", size = 0.5) +
  geom_line(data = mean_sim, color = "black", size = 1) +
  stat_summary(geom="ribbon", fun.data = mean_cl_boot, 
               conf.int=0.95, alpha = 0.0, linetype = "dashed", color = "black", size = .75)+
  geom_hline(yintercept = 6000, color = "red") + ## This will depend on pop starting size
      geom_hline(yintercept = 6000 * .1 + 6000, color = "midnightblue") + ## 10% wounding loss + harvest
  labs(x = "time (years)", 
       y = "harvest", title = "Adult Female Harvest per Year")+
    ylim(c(0, 20000))+
  theme_classic()
```




Adult Female harvest
```{r}
AM_harv <- mod_deaths_harv %>% 
  select(-dead_AF) %>% 
  filter(age_class == "adult") %>% 
  mutate(harvest = dead_AM)

mean_sim <- AM_harv %>% 
  group_by(year) %>% 
  summarise(harvest = mean(harvest),
            harvest_sd = sd(harvest)) %>% 
  mutate(upper_CI = harvest+harvest_sd, 
         lower_CI = harvest-harvest_sd)

ggplot(data = AM_harv,
                   aes(x = year, y = harvest)) +
  geom_line(aes(group = sim), color = "grey", size = 0.5) +
  geom_line(data = mean_sim, color = "black", size = 1) +
  stat_summary(geom="ribbon", fun.data = mean_cl_boot, 
               conf.int=0.95, alpha = 0.0, linetype = "dashed", color = "black", size = .75)+
  geom_hline(yintercept = 9600, color = "red") + ## This will depend on pop starting size
  geom_hline(yintercept = 9600 * .1 + 9600, color = "midnightblue") + ## 10% wounding loss + harvest
  labs(x = "time (years)", 
       y = "harvest", title = "Adult Male Harvest per Year")+
    ylim(c(0, 1e5))+
  theme_classic()
```


Prevalence
```{r prev}
base_count_popn <- simsout$counts %>% 
   filter(month %% 12 == 2) %>%
  group_by(sim, year, month) %>% 
  summarise(count = sum(population))

prev <- simsout$counts %>% 
   filter(month %% 12 == 2) %>%
  filter(disease == "yes" & population >= 1) %>% 
  group_by(sim, year, month) %>% 
  summarise(trueprev_count = n())

sum_prev <- base_count_popn %>% 
  full_join(prev, by = c("sim", "year", "month")) %>% 
  mutate(prop_true_prev = trueprev_count/count)


mean_sim <- sum_prev %>% 
  group_by(year) %>% 
  summarise(prop_true_prev = mean(prop_true_prev),
            prop_true_prev_sd = sd(prop_true_prev)) %>% 
  mutate(upper_CI = prop_true_prev+prop_true_prev_sd, 
         lower_CI = prop_true_prev-prop_true_prev_sd)


ggplot(data = sum_prev,
                   aes(x = year, y = prop_true_prev)) +
  geom_line(aes(group = sim), color = "grey", size = 0.5) +
  geom_line(data = mean_sim, color = "black", size = 1) +
  stat_summary(geom="ribbon", fun.data = mean_cl_boot, 
               conf.int=0.95, alpha = 0.0, linetype = "dashed", color = "black", size = .75)+
  labs(x = "time (years)", 
       y = "True Prevalence", title = "Prevalence over time")+
  theme_classic()

```


Check survival for each class (adult, juv, fawns) - *I don't think these are right*
```{r survivedf}
mod_deaths <- simsout$deaths %>% 
    filter(month %% 12 == 9) %>%
  filter(population > 0) %>% 
    mutate(IDfawn = case_when(age == 1 ~ 1, age != 1 ~  0)) %>% 
    mutate(IDjuv = case_when(age == 2 ~ 1, age != 2 ~  0)) %>% 
    mutate(IDadult = case_when(age > 2 ~ 1, age < 2 ~  0)) %>% 
    mutate(IDf = case_when(sex == "f" ~ 1, sex != "f" ~  0)) %>% 
    mutate(IDm = case_when(sex == "m" ~ 1, sex != "m" ~  0)) %>% 
      mutate(FawnCount = population * IDfawn) %>% 
      mutate(JuvCount = population * IDjuv) %>% 
      mutate(AFCount = population * IDadult * IDf) %>% 
      mutate(AMCount = population * IDadult * IDm)  %>% 
  mutate(age_class = ifelse(age == 1, "fawn",
                               ifelse(age == 2, "juv", "adult"))) %>% 
    mutate(year = round(year * .9)) %>% 
  group_by(sim, year,age_class) %>% 
  summarise(dead_fawns = sum(FawnCount),
            dead_juv = sum(JuvCount),
            dead_AF = sum(AFCount),
            dead_AM = sum(AMCount)) %>% 
  mutate_at(vars(dead_fawns, dead_juv, dead_AF, dead_AM), replace_na, 0)


mod_counts <- simsout$counts %>% 
    filter(month %% 12 == 9) %>%
  filter(population > 0) %>% 
    mutate(IDfawn = case_when(age == 1 ~ 1, age != 1 ~  0)) %>% 
    mutate(IDjuv = case_when(age == 2 ~ 1, age != 2 ~  0)) %>% 
    mutate(IDadult = case_when(age > 2 ~ 1, age < 2 ~  0)) %>% 
    mutate(IDf = case_when(sex == "f" ~ 1, sex != "f" ~  0)) %>% 
    mutate(IDm = case_when(sex == "m" ~ 1, sex != "m" ~  0)) %>% 
      mutate(FawnCount = population * IDfawn) %>% 
      mutate(JuvCount = population * IDjuv) %>% 
      mutate(AFCount = population * IDadult * IDf) %>% 
      mutate(AMCount = population * IDadult * IDm) %>% 
  mutate(age_class = ifelse(age == 1, "fawn",
                               ifelse(age == 2, "juv", "adult"))) %>% 
    mutate(year = round(year * .9)) %>% 
  group_by(sim, year,age_class) %>% 
  summarise(alive_fawns = sum(FawnCount),
            alive_juv = sum(JuvCount),
            alive_AF = sum(AFCount),
            alive_AM = sum(AMCount)) %>% 
  mutate_at(vars(alive_fawns, alive_juv, alive_AF, alive_AM), replace_na, 0)

survival_df <- full_join(mod_deaths, mod_counts, by = c("sim", "year", "age_class"))
```


fawn survival
```{r}
fawn_sur <- survival_df %>% 
  filter(age_class == "fawn") %>% 
  mutate(survival = alive_fawns/ (alive_fawns + dead_fawns))

mean_sim <- fawn_sur %>% 
  group_by(year) %>% 
  summarise(survival = mean(survival),
            survival_sd = sd(survival)) %>% 
  mutate(upper_CI = survival+survival_sd, 
         lower_CI = survival-survival_sd)

ggplot(data = fawn_sur,
                   aes(x = year, y = survival)) +
  geom_line(aes(group = sim), color = "grey", size = 0.5) +
  geom_line(data = mean_sim, color = "black", size = 1) +
  stat_summary(geom="ribbon", fun.data = mean_cl_boot, 
               conf.int=0.95, alpha = 0.0, linetype = "dashed", color = "black", size = .75)+
  geom_hline(yintercept = .6, color = "red") + ## This will depend on pop starting size
  labs(x = "time (years)", 
       y = "survival", title = "Fawn survival per Year")+
  theme_classic()
```

juvenile survival
```{r}
juv_sur <- survival_df %>% 
  filter(age_class == "juv") %>% 
  mutate(survival = alive_juv/ (alive_juv + dead_juv))

mean_sim <- juv_sur %>% 
  group_by(year) %>% 
  summarise(survival = mean(survival),
            survival_sd = sd(survival)) %>% 
  mutate(upper_CI = survival+survival_sd, 
         lower_CI = survival-survival_sd)

ggplot(data = juv_sur,
                   aes(x = year, y = survival)) +
  geom_line(aes(group = sim), color = "grey", size = 0.5) +
  geom_line(data = mean_sim, color = "black", size = 1) +
  stat_summary(geom="ribbon", fun.data = mean_cl_boot, 
               conf.int=0.95, alpha = 0.0, linetype = "dashed", color = "black", size = .75)+
  geom_hline(yintercept = .8, color = "red") + ## This will depend on pop starting size
  labs(x = "time (years)", 
       y = "survival", title = "Juvenile Survival per Year")+
  theme_classic()
```



Adult Female survival
```{r}
AF_sur <- survival_df %>% 
  filter(age_class == "adult") %>% 
  select(-c(dead_AM, alive_AM)) %>% 
  mutate(survival = alive_AF/ (alive_AF + dead_AF))

mean_sim <- AF_sur %>% 
  group_by(year) %>% 
  summarise(survival = mean(survival, na.rm = T),
            survival_sd = sd(survival, na.rm = T)) %>% 
  mutate(upper_CI = survival+survival_sd, 
         lower_CI = survival-survival_sd)

ggplot(data = AF_sur,
                   aes(x = year, y = survival)) +
  geom_line(aes(group = sim), color = "grey", size = 0.5) +
  geom_line(data = mean_sim, color = "black", size = 1) +
  stat_summary(geom="ribbon", fun.data = mean_cl_boot, 
               conf.int=0.95, alpha = 0.0, linetype = "dashed", color = "black", size = .75)+
  geom_hline(yintercept = .82, color = "red") + ## This will depend on pop starting size
  labs(x = "time (years)", 
       y = "survival", title = "Adult Female Survival per Year")+
  theme_classic()
```





Adult Male survival
```{r}
AM_sur <- survival_df %>% 
  filter(age_class == "adult") %>% 
  select(-c(dead_AF, alive_AF)) %>% 
  mutate(survival = alive_AM/ (alive_AM + dead_AM))

mean_sim <- AM_sur %>% 
  group_by(year) %>% 
  summarise(survival = mean(survival, na.rm = T),
            survival_sd = sd(survival, na.rm = T)) %>% 
  mutate(upper_CI = survival+survival_sd, 
         lower_CI = survival-survival_sd)

ggplot(data = AM_sur,
                   aes(x = year, y = survival)) +
  geom_line(aes(group = sim), color = "grey", size = 0.5) +
  geom_line(data = mean_sim, color = "black", size = 1) +
  stat_summary(geom="ribbon", fun.data = mean_cl_boot, 
               conf.int=0.95, alpha = 0.0, linetype = "dashed", color = "black", size = .75)+
  geom_hline(yintercept = .5, color = "red") + ## This will depend on pop starting size
  labs(x = "time (years)", 
       y = "survival", title = "Adult Male Survival per Year")+
  theme_classic()
```

